services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - elastic-network

  pgadmin:
    restart: always
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - elastic-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      discovery.type: 'single-node'
      bootstrap.memory_lock: true
      xpack.security.enabled: true
      xpack.security.enrollment.enabled: true
      xpack.security.autoconfiguration.enabled: true
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: '-Xms128m -Xmx512m'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -s --fail http://localhost:9200/_cluster/health | grep -q ''"status":"green"'' || curl -s --fail http://localhost:9200/_cluster/health | grep -q ''"status":"yellow"''',
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    restart: always
    environment:
      # elasticsearch.ssl.verificationMode: 'none'
      # xpack.security.enabled: false
      xpack.security.http.ssl.enabled: true
      # xpack.security.transport.ssl.enabled: true
      # csp.strict: false
      # csp.warnLegacyBrowsers: true
      # xpack.security.enrollment.enabled: true
      ELASTICSEARCH_HOSTS: http://localhost:9200
      # ELASTICSEARCH_SERVICEACCOUNTTOKEN: 'AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL215LXRva2VuOm9vZ2duSm5vUzRtaWlIbmNBdE8tT1E'
      ELASTIC_USERNAME: ${KIBANA_USERNAME}
      ELASTIC_PASSWORD: ${KIBANA_PASSWORD}
      # ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: './config/certs/ca/ca.crt'
      # XPACK_SECURITY_ENCRYPTIONKEY: 'GlMsRqxowLRcx/pTimUno8YliKoszQ0+4TLX9II3I7w='
      # XPACK_REPORTING_ENCRYPTIONKEY: 'jFSghBN8mzmrikLoCmEFdiVuxein1IYVjIDCdXJHhwg='
      # XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 'gryVRl5jwDcpWMQfi4eSQ2VrydRa7Z5j75zM0js4Pgs='
    depends_on:
      - elasticsearch
    healthcheck:
      test: ['CMD-SHELL', 'curl -s --fail http://localhost:5601/api/status']
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elastic-network

volumes:
  elastic-data:
    driver: local
  kibanadata:
    driver: local

networks:
  elastic-network:
    driver: bridge
